Add UI for enrolling in Feature Configuration
mozilla-extensions/nimbus-devtools pull request #17
Opened 2024-05-22 14:21 UTC by RJAK11

Implemented feature to allow users to paste an Experiment feature configuration JSON and select a feature ID to enroll into an experiment.

Fixes #5

2024-05-22 19:31 UTC, brennie requested changes
There are some formatting issues that will be fixed by rebasing on top of main and running `npm run fix`

2024-05-22 19:31 UTC, brennie commented on src/ui/components/FeatureConfigPage.tsx
> +    const jsonData = jsonInput;
Why rebind here?

2024-05-23 19:00 UTC, RJAK11 commented on src/ui/components/FeatureConfigPage.tsx
> +    try {
I think both `JSON.parse(jsonInput)` and `browser.experiments.nimbus.enrollWithFeatureConfig` can throw errors so I assumed that we should use try/catch

2024-05-23 19:26 UTC, brennie approved these changes
LGTM

2024-05-23 19:26 UTC, brennie commented on src/apis/nimbus.js
> +          async enrollWithFeatureConfig(featureId, jsonData, isRollout) {
lets rename `jsonData` to `featureValue`

2024-05-23 19:26 UTC, brennie commented on src/types/global.d.ts
> +}
neat!

2024-05-23 19:26 UTC, brennie commented on src/ui/components/FeatureConfigPage.tsx
> +    try {
Lets move the try/catch to just around the JSON.parse and API call.

2024-05-23 19:26 UTC, brennie commented on src/ui/index.css
> +    font-family: "Segoe UI", Tahoma, Verdana, sans-serif;
Lets use: `"Helvetica Neue", Helvetica, Arial, sans-serif;`

2024-05-23 19:26 UTC, brennie commented on src/ui/index.css
> +    background-color: #44144c;
In a followup we should clean up the CSS to use constants for a lot of these, but we're in the prototype phase so lets not worry now.

2024-05-23 19:51 UTC, merged