Resolved npm run watch missing dist file error by adding the nimbus.json schema file to the parseManifest function
mozilla-extensions/nimbus-devtools pull request #3
Opened 2023-08-15 23:20 UTC by thessakranendonk

2023-08-15 23:21 UTC, thessakranendonk commented
Please let me know if this is the correct solution :)

2023-08-16 16:28 UTC, brennie requested changes
Ideally commit message summaries should be in the imperative mood, i.e., tell me what the commit does, not what it did.

e.g., I would rewrite this commit message as:

"Always copy API schemas in manifest build task"

2023-09-01 10:46 UTC, thessakranendonk commented on bin/build-manifest.mjs
> +    }
Perfect thank you! I  have updated the code.

2023-09-01 13:10 UTC, brennie requested changes

2023-09-01 13:16 UTC, thessakranendonk commented on bin/build-manifest.mjs
> +    // nimbus.json schema
Removed it!

2023-09-01 14:37 UTC, brennie approved these changes

2023-09-01 14:37 UTC, brennie commented
Can you squash your commits together into a single commit?

2023-09-01 15:43 UTC, thessakranendonk commented
Sure! Did not know that was possible haha! All done. How would you like the merging process to go? Does the reviewer merge or the branch owner?

2023-09-01 15:47 UTC, brennie commented
You should have permission to click the "Rebase and merge" button, so I'll let you do the honours.

2023-09-01 15:48 UTC, merged

2023-09-01 15:48 UTC, brennie commented
Fixes #2