Switch to a UI framework
mozilla-extensions/nimbus-devtools pull request #36
Opened 2024-07-04 19:18 UTC by RJAK11

Replace bespoke CSS with React Bootstrap for cleaner and more maintainable styling.

Fixes #24

2024-07-04 20:10 UTC, jaredlockhart reviewed
Okay!  Overall this looks fantastic, great job 👏 👏 👏 

Code is very clean and idiomatic, easy to read, very nicely laid out.

I put in some suggestions, some questions, it's late today so I'll just leave it like that and you can go through it together with @brennie when they're back on Monday.

But this is great, great job @RJAK11 🎉 🎉 🎉 🎉

2024-07-04 20:10 UTC, jaredlockhart commented on src/ui/components/JEXLDebuggerPage.tsx
> +                typeof value === "boolean" ? (
Oh in cases like this it's usually nicer to write it as

```js
["number", "string", "boolean"].includes(typeof value)
```

2024-07-04 20:10 UTC, jaredlockhart commented on src/ui/components/RecipeEnrollmentPage.tsx
> +  }, []);
Even if we do want to do this, we don't want to include the same logic and set of constants multiple times so we'd want to pull this out into a little utility file.

2024-07-04 20:10 UTC, jaredlockhart commented on src/ui/components/SettingsPage.tsx
> +                  collectionId !== PREVIEW_COLLECTION
Similarly here you could write this as 

```js
![LIVE_COLLECTION, PREVIEW_COLLECTION].includes(collectionId)
```

Makes it easier to change the list of things to check later.

2024-07-04 20:10 UTC, jaredlockhart commented on src/ui/components/SettingsPage.tsx
>                checked={forceSync === true}
You shouldn't need to write `=== true` right?

2024-07-04 20:10 UTC, jaredlockhart commented on src/ui/components/Sidebar.tsx
> +        className="sidebar__link fw-medium p-4 dark-font"
Do we still need the `sidebar__link` class?  Could it be written using bootstrap classes?

2024-07-04 20:10 UTC, jaredlockhart commented on src/ui/components/Sidebar.tsx
> -    </div>
If you're repeating the components here like this, you could just treat it as a loop

```js
[
  ["/experiment-feature-config", "Feature Configuration Enrollment"],
  ...
].map((path, label) => (
        <Nav.Link
        as={Link}
        to={path}
        className="sidebar__link fw-medium p-4 dark-font"
      >
        {label}
      </Link>
));
```

2024-07-09 14:01 UTC, brennie requested changes

2024-07-09 14:01 UTC, brennie commented on src/ui/index.css
> +    border-top: 2px solid rgb(212, 208, 208);
css custom props for all the colours please. And can we use hex for everything that doesnt require alpha channel?

2024-07-09 14:01 UTC, brennie commented on src/ui/components/ExperimentBrowserPage.tsx
> +      <h1 className="light-font my-3 fw-bold fs-3">{status} Experiments</h1>
The Settings page has an inconsistent (monospace) header

2024-07-09 17:05 UTC, RJAK11 commented on src/ui/index.css
>  }
I wanted to reuse .primary-fg but then the pseudo-classes :hover and :active for option-button would apply to everything else that uses .primary-fg. Unless there is a different way of doing it?

2024-07-09 17:10 UTC, brennie commented on src/ui/index.css
>  }
What I meant was the button should have `class="primary-fg option-button"` and then remove the `option-button` style and only keep `option-button:hover`. Sorry, I'm realizing as I type this that I wasn't clear.

2024-07-09 17:13 UTC, brennie approved these changes
r+ once all the unnecessary `!important` is removed.

2024-07-09 17:13 UTC, brennie commented on src/ui/index.css
> +    font-size: 0.8rem !important;
We shouldn't need any `!important` overrides for rules, since all of our custom rules are last in the cascade.

2024-07-09 17:13 UTC, brennie commented on src/ui/index.css
> +.light-background {
nit: rename `.light-bg` or similar.

2024-07-09 17:55 UTC, merged